#!/bin/sh
# my opener

mime=$(file --mime-type -b "$1")

case "$mime" in
    text/*)
        exec xfce4-terminal --title="Text Edit $($1)" -x micro "$1"
        ;;

    application/zip|application/x-tar|application/x-compressed-tar|application/x-bzip2|application/x-7z-compressed|application/x-rar|application/x-xz)
        exec xarchiver "$1"
        ;;

    image/*)
        exec xdg-open "$1"
        ;;

    video/*|audio/*)
        exec xdg-open "$1"
        ;;

    *)
        exec xdg-open "$1"
        ;;
esac
