#!/usr/bin/env bash

# Merge packages.x86_64.orig with pacman -Qqen to packages.x86_64 and delete duplicate entries
comm -13 <(sort packages.x86_64.orig) <(pacman -Qqen | sort) >> packages.x86_64
sort -u -o packages.x86_64 packages.x86_64


# arch-install-scripts-31-1  dosfstools-4.2-5  erofs-utils-1.8.10-1  libburn-1.5.6-1  libisoburn-1.5.6-1
#             libisofs-1.5.6-1  mtools-1:4.0.49-1  squashfs-tools-4.7.4-1  archiso-87-1