#!/bin/bash

#!/bin/bash

# __   _____  _   _ _   _ _____  __
# \ \ / / _ \| | | | \ | |_ _\ \/ /
#  \ V / | | | | | |  \| || | \  /
#   | || |_| | |_| | |\  || | /  \
#   |_| \___/ \___/|_| \_|___/_/\_\
#
# Lisence GPL3
# Homepage: https://github.com/apapamarkou/younix
# Author: Andrianos Papamarkou
# Email: papamarkoua@gmail.com

# Script to set up Wine, Winetricks, and Yabridge for Windows VST plugin support

clear
echo "Wine, Winetricks, and Yabridge Setup Script"
echo "--------------------------------------------"
echo
echo "This script will make do nessary actions to make possible to install and use Windows VST and VST3 plugins as it was native Linux plugins."
echo "Wine, Winetricks, and Yabridge will be installed and configured"
echo "managing VST plugins on your system."
echo

# Confirmation
read -p "Do you want to proceed? (Y/n) " -n 1
echo
if [[ $REPLY =~ ^[Nn]$ ]]
then
    exit 1
fi

# Install necessary packages
sudo pacman -S --needed  --noconfirm wine-staging winetricks yabridge yabridgectl

# Define VST plugin paths
VST_PATH1="$HOME/.wine/drive_c/Program Files/Steinberg/VstPlugins"
VST_PATH2="$HOME/.wine/drive_c/Program Files/Common Files/VST3"
VST_PATH3="$HOME/.wine/drive_c/Program Files/VSTPlugins"

# Function to print progress messages
print_message() {
  echo -e "\n[INFO] $1\n"
}

# Self-update Winetricks
print_message "Updating Winetricks..."
sudo winetricks --self-update

# Install necessary Winetricks component
print_message "Installing vcrun6sp6 via Winetricks..."
winetricks vcrun6sp6

# Open Wine configuration
print_message "Opening Wine configuration..."
winecfg

# Create required directories for VST plugins
print_message "Creating directories for VST plugins..."
mkdir -p "$VST_PATH1"
mkdir -p "$VST_PATH2"
mkdir -p "$VST_PATH3"

# Add directories to Yabridge
print_message "Adding Steinberg VSTPlugins to Yabridge..."
yabridgectl add "$VST_PATH1"

print_message "Adding Common VST3 plugins to Yabridge..."
yabridgectl add "$VST_PATH2"

print_message "Adding VSTPlugins to Yabridge..."
yabridgectl add "$VST_PATH3"

print_message "Setup complete!"
