#!/bin/bash

# get the script dir
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# get the project root
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")/iso"
ISO_ROOT="$PROJECT_ROOT/iso/airootfs"

echo "Project root: $PROJECT_ROOT"

# sync the files from prep.txt to $ISO_ROOT
LIST_FILE="$SCRIPT_DIR/prep.txt"
DEST="$ISO_ROOT"
mkdir -p "$DEST"
while IFS= read -r path || [ -n "$path" ]; do
    # skip empty lines and comments
    [[ -z "${path// }" || "${path:0:1}" == "#" ]] && continue

    SRC="$PROJECT_ROOT/$path"

    if [ -e "$SRC" ]; then
        echo "Syncing: $SRC -> $DEST"
        rsync -a --delete --relative "$PROJECT_ROOT/./$path" "$DEST"
    else
        echo "⚠️ Missing: $SRC"
    fi
done < "$LIST_FILE"